ARG BaseImage
FROM $BaseImage
ENV PYTHONUNBUFFERED 1
WORKDIR /code
COPY . .
EXPOSE 8000
RUN pip install psycopg2==2.8.2
RUN pip install mysqlclient==1.4.2
RUN pip install cx-Oracle==7.1.3
RUN pip install dj-database-url==0.5.0
RUN pip install -r requirements.txt
RUN python manage.py makemigrations
RUN python manage.py migrate
CMD ["uwsgi", "uwsgi-nginx.ini"]
