language: generic
sudo: required
services:
  - docker


#before_install:
#  - docker build -t datasciencedotuniversity/dockeer-react -f Dockerfile.dev .
#script:
#  - docker run -e CI=true datasciencedotuniversity/dockeer-react npm run test

after_success:
  - docker-compose -f django-polls-build.yml build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push coding4startups/django-polls:nginx
  - docker push coding4startups/mynginx:latest
  - docker push coding4startups/django:latest
  - docker push coding4startups/uwsgi:latest

deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-3-634261840555"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRECT_KEY