version: "3.7"
services:

# fake Service to build "django" Base Image
  django:
    build:
      context: base_image/
      dockerfile: Dockerfile.mydjango
    image: coding4startups/django:latest
    entrypoint: /bin/true

#fake Service to build "uwsgi" Base Image
  uwsgi:
    build:
      context: base_image/
      dockerfile: Dockerfile.myuwsgi
    image: coding4startups/uwsgi:latest
    entrypoint: /bin/true

# fake Service to build "mynginx" Image
  mynginx:
    depends_on:
      - django
    build:
      context: django-polls/
      dockerfile: Dockerfile.nginx
      args:
        BaseImage: coding4startups/django:latest
    image: coding4startups/mynginx:latest
    entrypoint: /bin/true

# fake Service to build "django-polls" Image
  django-polls:
    depends_on:
      - uwsgi
    build:
      context: django-polls/
      dockerfile: Dockerfile.polls
      args:
        BaseImage: coding4startups/uwsgi:latest
    image: coding4startups/django-polls:nginx
    entrypoint: /bin/true
