version: "3.7"



services:
# Initilization Service
# please run with:
# docker-compose -f django-polls-deploy.yml -f django-polls-ops.yml run --rm init
  init:
    image: example/django-polls:nginx
    networks:
      - polls_net
    env_file:
      - deployment.env
    command: ["/bin/bash", "-c",
              "python manage.py migrate;
               python manage.py loaddata initial_data.json;
               python manage.py createsuperuser"]
    tty: true

# Database Clonning Service
# Performs full, on-line Backup of "db" Service onto "polls_clone" Volume
# Removes previous backup before taking fresh one
# please run with:
# docker-compose -f django-polls-deploy.yml -f django-polls-ops.yml run --rm db-clone

 
